---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-eks-
resources:
  - ../../base-eks
  - namespace.yaml
  - secret.yaml
  - sa.yaml
patches:
  - path: deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: bgd
      labelSelector: "app=bgd"
commonLabels:
  env: dev-eks-bgd
# BEGIN ANSIBLE MANAGED BLOCK dev-eks
images:
  - name: php81-bgd-alpine
    newName: <quay-registry>/automationiberia/php81-bgd-alpine
    newTag: 9.5.0
# END ANSIBLE MANAGED BLOCK dev-eks
...
