---
# Secret taken from quay registry organization robot account
apiVersion: v1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: pipelines-demo-pull-secret
  namespace: pipelines-demo
data:
  .dockerconfigjson: <docker_config_in_json_and_base64>
type: kubernetes.io/dockerconfigjson
...
