---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '0'
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: openshift-pipelines-operator-rh
  namespace: openshift-operators
  labels:
    operators.coreos.com/openshift-pipelines-operator-rh.openshift-operators: ''
spec:
  channel: pipelines-1.9
  installPlanApproval: Automatic
  name: openshift-pipelines-operator-rh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
#  startingCSV: openshift-pipelines-operator-rh.v1.9.0
...
