---
apiVersion: v1
kind: Secret
metadata:
  name: 1979710-acm-eks-pull-secret
data:
  .dockerconfigjson:  # Get Token From https://access.redhat.com/terms-based-registry/
type: kubernetes.io/dockerconfigjson
...
