---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: app-gitops-placement-eks
  namespace: openshift-gitops
spec:
  clusterSets:
    - eksclusterset
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: vendor
          operator: "In"
          values:
          - EKS
...
