---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: pipeline
  namespace: pipelines-demo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
secrets:
  - name: pipelines-demo-pull-secret
imagePullSecrets:
  - name: pipelines-demo-pull-secret
...
