---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-runner-rolebinding
  namespace: demo-gitlab-runner
subjects:
  - kind: ServiceAccount
    name: gitlab-runner-sa
    namespace: demo-gitlab-runner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-runner-role
...
